---
- hosts: webservers
  become: true #use sudo

  tasks:

   - name: update the apt cache
     apt:
       update_cache: yes

   - name: Install OpenJDK java
     apt:
       name: openjdk-8-jdk
       state: present

   - name: SET JAVA_HOME
     shell: sudo echo "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" >> ~/.bashrc




